/* tslint:disable */
/* eslint-disable */
/**
 * frog-db rest interface
 * A frog-db rest interface generated by oapi-codegen
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: serhii_syrota@knu.ua
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

